[project]
name = "siliconai"
version = "0.1.0"
description = "Deep generative models for fast silicon tracking detector simulation"
authors = [{ name = "Tadej Novak", email = "tadej.novak@cern.ch" }]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MPL-2.0" }
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Environment :: GPU",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
