name = "Continuous Transformer"

[data]
type = "ActsHits"
input_dim = []
split_ratio = [0.5, 0.25, 0.25]
batch_size = 10000
workers = 12

[data.conversion]
input = "ACTS_Muon_100GeV_Barrel_hits.h5"
output = "ACTS_Muon_100GeV_Barrel_hits_continuous.pkl"
columns_float = ["lx", "ly"]

[model]
type = "ContinuousTransformer"
sequence_length = 25
model_dim = 128                # 512
encoder_layers = 8             # 6
heads = 8                      # 8
feedforward_dim = 512          # 2048
activation = "gelu"
dropout = 0.1
loss = "mse_loss"

[training]
epochs = 2000
early_stopping = 0

optimizer = "Adam"
learning_rate = 0.0001
weight_decay = 0.0
