name = "Discrete Transformer Large"

[data]
type = "ActsHits"
input_dim = [4350, 3, 6774, 7446, 12308, 12309, 1415]
split_ratio = [0.5, 0.25, 0.25]
batch_size = 800
workers = 12
padding_token = 999999
end_token = 1000001
random_int = 10000

[data.conversion]
input = "ACTS_Muon_pt70-90_eta005-025.h5"
output = "ACTS_Muon_pt70-90_eta005-025_discrete.pkl"
columns_integer = [
    "geometry_id",
    "particle_type",
    "lxq",
    "lyq",
    "tpxq",
    "tpyq",
    "tpzq",
]

[model]
type = "DiscreteTransformer"
sequence_length = 45
model_dim = 256              # 512
encoder_layers = 6           # 6
heads = 8                    # 8
feedforward_dim = 1025       # 2048
activation = "gelu"
dropout = 0.1

[training]
compile = true

epochs = 10000
checkpoint_interval = 200
early_stopping = 0

optimizer = "AdamW"
learning_rate = 0.0003
weight_decay = 0.01
gradient_clipping = 5.0

[training.scheduler]
type = "CosineAnnealingWarmRestarts"
interval = "step"
T_0 = 50
