name = "Discrete Transformer Narrow"

[data]
type = "ActsHits"
input_dim = [3811, 3, 6773, 7576]
split_ratio = [0.5, 0.25, 0.25]
batch_size = 2048
workers = 12

[data.conversion]
input = "ACTS_Muon_100GeV_Barrel_Narrow_hits.h5"
output = "ACTS_Muon_100GeV_Barrel_Narrow_hits_discrete.pkl"
columns_integer = ["geometry_id", "particle_type", "lxq", "lyq"]

[model]
type = "DiscreteTransformer"
sequence_length = 35
model_dim = 128              # 512
encoder_layers = 3           # 6
heads = 4                    # 8
feedforward_dim = 512        # 2048
activation = "gelu"
dropout = 0.1

[training]
epochs = 50
early_stopping = 0

optimizer = "Adam"
learning_rate = 0.001
weight_decay = 0.0
