name = "FashionMNIST ConvVAE Conditioning"

[data]
type = "FashionMNIST"
input_dim = [1, 28, 28]
batch_size = 64

[model]
type = "ConvVAE"
latent_dim = 128
encoder_layers = [[32, 3, 2, 1], [64, 3, 2, 1], [128, 3, 2, 1]]
decoder_layers = [[128, 3, 2, 1], [64, 3, 2, 1], [32, 3, 2, 1]]
activation = "LeakyReLU"
activation_parameters = [0.2]
batch_norm = false
dropout = 0.0
loss = "logcosh_loss"
loss_parameters = [10.0, 1.0]

[model.embedding]
input_dim = 10
latent_dim = 16

[training]
epochs = 50
early_stopping = 3

optimizer = "Adam"
learning_rate = 0.001
weight_decay = 0.0
