name = "MNIST VAE Embedding"

[data]
type = "MNIST"
input_dim = [28, 28]
batch_size = 100

[model]
type = "EmbeddingVAE"
latent_dim = 200
encoder_layers = [400, 400]
decoder_layers = [400, 400]
activation = "LeakyReLU"
activation_parameters = [0.2]
batch_norm = false
dropout = 0.0

[model.embedding]
class_count = 10
latent_dim = 16
