name = "Test Discrete Transformer"

[data]
type = "ActsHits"
input_dim = [2667, 3]
split_ratio = [0.8, 0.1, 0.1]
batch_size = 2
workers = 12

[data.conversion]
input = "ACTS_Muon_100GeV_Barrel_hits_test.h5"
output = "ACTS_Muon_100GeV_Barrel_hits_test_discrete.pkl"
columns_integer = ["geometry_id", "particle_type"]

[model]
type = "DiscreteTransformer"
sequence_length = 25
model_dim = 16               # 512
encoder_layers = 3           # 6
heads = 2                    # 8
feedforward_dim = 64         # 2048
activation = "gelu"
dropout = 0.1

[training]
compile = true

epochs = 5
checkpoint_interval = 2
early_stopping = 0

optimizer = "Adam"
learning_rate = 0.03
weight_decay = 0.0

[training.scheduler]
type = "AttentionWarmupScheduler"
interval = "step"
warmup_steps = 1000
