name = "TRKNtuple VAE"

[data]
type = "TRKNtuple"
input_dim = 5
batch_size = 128

[data.conversion]
input = "TRKNtuple_mu_Pt100to150_Eta020to025pm.root"
output = "TRKNtuple_mu_Pt100to150_Eta020to025pm.npy"

[model]
type = "BasicVAE"
latent_dim = 16
encoder_layers = [128, 64]
decoder_layers = [64, 128]
activation = "LeakyReLU"
# activation_parameters = [0.2]
batch_norm = false
dropout = 0.0
loss = "mse_loss"

[model.conditioning]
input_dim = 4
latent_dim = 16

[training]
epochs = 50
early_stopping = 3

optimizer = "Adam"
learning_rate = 0.001
weight_decay = 0.0
